services:
  node1:
    image: ghcr.io/p4trickweiss/distributed-cache:latest
    container_name: raft-node1
    volumes:
      - node1-data:/data
    environment:
      - DCACHE_NODE_ID=node1
      - DCACHE_NODE_DATA_DIR=/data
      - DCACHE_HTTP_BIND_ADDR=0.0.0.0:11000
      - DCACHE_RAFT_BIND_ADDR=node1:12000
    ports:
      - "11001:11000"
    networks:
      - raft-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:11000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  node2:
    image: ghcr.io/p4trickweiss/distributed-cache:latest
    container_name: raft-node2
    volumes:
      - node2-data:/data
    environment:
      - DCACHE_NODE_ID=node2
      - DCACHE_NODE_DATA_DIR=/data
      - DCACHE_HTTP_BIND_ADDR=0.0.0.0:11000
      - DCACHE_RAFT_BIND_ADDR=node2:12000
      - DCACHE_CLUSTER_JOIN_ADDR=node1:11000
    ports:
      - "11002:11000"
    networks:
      - raft-network
    depends_on:
      node1:
        condition: service_healthy

  node3:
    image: ghcr.io/p4trickweiss/distributed-cache:latest
    container_name: raft-node3
    volumes:
      - node3-data:/data
    environment:
      - DCACHE_NODE_ID=node3
      - DCACHE_NODE_DATA_DIR=/data
      - DCACHE_HTTP_BIND_ADDR=0.0.0.0:11000
      - DCACHE_RAFT_BIND_ADDR=node3:12000
      - DCACHE_CLUSTER_JOIN_ADDR=node1:11000
    ports:
      - "11003:11000"
    networks:
      - raft-network
    depends_on:
      node1:
        condition: service_healthy

networks:
  raft-network:
    driver: bridge

volumes:
  node1-data:
  node2-data:
  node3-data:
