# https://taskfile.dev

version: "3"

tasks:
  run:
    desc: Run the application
    cmds:
      - go run cmd/main.go

  build:
    desc: Build the Docker image
    cmds:
      - docker build -f build/Dockerfile -t ghcr.io/p4trickweiss/distributed-cache:latest .

  docker-compose:
    desc: Run the docker-compose file
    cmds:
      - docker compose -f deployments/docker-compose.yml up

  proto:generate:
    desc: Generate gRPC code from proto files
    cmds:
      - protoc -I=proto --go_out=internal/grpc --go_opt=paths=source_relative --go-grpc_out=internal/grpc --go-grpc_opt=paths=source_relative grpcserver.proto
