# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  app:
    taskfile: minicacher/Taskfile.yml
    dir: minicacher

tasks:
  test:unit:
    desc: Run unit tests
    cmds:
      - task: app:test:unit
