apiVersion: cache.p4trickweiss.dev/v1alpha1
kind: DistributedCache
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: distributedcache-sample
spec:
  # TODO(user): Add fields here
